
INSERT INTO `` (`idcustomer`,`user_iduser`,`name`,`representative`,`email`,`address`) VALUES (6,19,'Магазин \"Соседи\"','Перников Сергей Николаевич','sosedi.minsk@gmail.com','Беларусь, г.Минск, ул. Л.Беды 2');
INSERT INTO `` (`idcustomer`,`user_iduser`,`name`,`representative`,`email`,`address`) VALUES (7,20,NULL,'Черников Олег Сергеевич','oleg@gmail.com','Беларусь,г.Туров,ул. Речная 45');
INSERT INTO `` (`idcustomer`,`user_iduser`,`name`,`representative`,`email`,`address`) VALUES (8,21,'Магазин \"Простор\"','Дмитрук Дарья Юрьевна','dashka@mail.ru','Беларусь,г.Смолевичи,ул.Зеркальная 1 кв.23');

INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (1,1,32,25);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (2,1,48,13);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (3,1,34,35);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (4,1,35,87);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (5,1,36,23);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (6,1,4,3);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (7,1,5,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (8,1,6,8);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (9,1,7,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (10,1,8,50);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (11,1,9,25);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (12,1,47,67);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (13,2,32,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (14,2,4,12);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (15,2,36,9);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (16,2,5,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (17,2,37,12);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (18,2,6,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (19,2,7,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (20,2,8,8);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (21,2,44,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (22,2,12,9);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (23,2,45,9);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (24,2,46,12);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (25,2,47,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (26,7,32,31);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (27,7,1,22);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (28,7,33,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (29,7,2,14);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (30,7,34,22);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (31,7,3,6);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (32,7,35,14);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (33,7,4,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (34,7,7,31);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (35,7,25,22);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (36,7,45,31);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (37,7,46,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (38,8,32,31);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (39,8,2,31);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (40,8,3,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (41,9,1,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (42,9,2,30);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (43,9,3,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (44,9,36,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (45,9,4,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (46,9,38,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (47,9,10,12);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (48,9,27,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (49,9,28,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (50,9,29,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (51,10,3,7);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (52,10,4,1);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (53,10,42,7);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (54,11,2,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (55,12,2,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (56,13,2,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (57,14,2,5);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (58,15,5,4);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (59,16,4,4);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (60,17,27,7);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (61,18,4,1);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (62,19,48,35);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (63,19,4,10);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (64,19,5,26);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (65,19,37,26);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (66,19,6,35);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (67,19,7,25);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (68,19,8,15);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (69,19,44,25);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (70,19,47,26);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (71,20,3,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (72,21,3,20);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (73,22,3,3);
INSERT INTO `` (`id_order_product`,`order_idorder`,`product_idproduct`,`amount`) VALUES (74,23,45,67);

INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (1,2,6,'07/12/2019','14/12/2019','rejected',2500);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (2,1,6,'08/12/2019','15/12/2019','adopted',1790);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (3,3,7,'05/12/2019','15/12/2019','adopted',330);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (4,2,8,'09/08/2019','15/12/2019','adopted',1090);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (5,1,8,'01/12/2019','15/12/2019','adopted',1000);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (6,3,8,'09/08/2019','15/12/2019','adopted',2000);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (7,3,8,'09/12/2019','18/12/2019','rejected',468.06);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (8,2,8,'09/12/2019','19/12/2019','rejected',163.35);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (9,2,6,'09/12/2019','18/12/2019','processed',215.26);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (10,1,6,'09/12/2019','10/12/2019','rejected',23.22);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (11,3,6,'09/12/2019','16/12/2019','processed',6);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (12,3,6,'09/12/2019','04/12/2019','processed',6);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (13,3,6,'09/12/2019','04/12/2019','processed',6);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (14,3,6,'09/12/2019','04/12/2019','adopted',6);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (15,3,6,'09/12/2019','02/12/2019','processed',5.8);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (16,2,6,'09/12/2019','04/12/2019','adopted',8.04);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (17,2,6,'09/12/2019','26/11/2019','processed',8.89);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (18,1,6,'09/12/2019','10/12/2019','rejected',2.01);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (19,1,6,'09/12/2019','17/12/2019','rejected',325.35);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (20,3,6,'10/12/2019','24/12/2019','posted',37.8);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (21,3,6,'10/12/2019','24/12/2019','posted',37.8);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (22,3,6,'10/12/2019','17/12/2019','posted',5.67);
INSERT INTO `` (`idorder`,`sklad_idsklad`,`customer_idcustomer`,`orderdate`,`deliverydate`,`processing`,`cost`) VALUES (23,3,7,'10/12/2019','17/12/2019','rejected',132.3);

INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (1,'Кока-кола 0,25л','газированная','бутылка',1.16);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (2,'Кока-кола 0,5л','газированная','бутылка',1.2);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (3,'Кока-кола 1,5л','газированная','бутылка',1.89);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (4,'Кока-кола Зеро 1,5л','газированная','бутылка',2.01);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (5,'Кока-кола Зеро 0,5л','газированная','бутылка',1.45);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (6,'Кока-кола Зеро 1л','газированная','бутылка',1.7);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (7,'Кока-кола Черри 1л','газированная','бутылка',1.61);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (8,'Кока-кола Черри 2л','газированная','бутылка',2.01);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (9,'Кока-кола Черри 0,25л','газированная','бутылка',1.13);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (10,'Фанта Апельсин 0,5л','газированная','бутылка',1.13);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (11,'Фанта  Мандарин 0,5л','газированная','бутылка',1.15);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (12,'Фанта Апельсин 1,5л','газированная','бутылка',1.76);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (13,'Фанта Апельсин 2л','газированная','бутылка',2.4);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (14,'Фанта  Мандарин 1л','газированная','бутылка',1.52);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (15,'Спрайт Лайм-Мята 1л','газированная','бутылка',1.35);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (16,'Спрайт Лайм-Мята 2л','газированная','бутылка',2.1);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (17,'Спрайт Лайм-Мята 0,5л','газированная','бутылка',1.23);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (18,'Спрайт Лимон 1л','газированная','бутылка',1.42);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (19,'Спрайт Лимон 2л','газированная','бутылка',2.05);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (20,'Швепс Тоник 1л','газированная','бутылка',1.81);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (21,'Швепс Тоник 2л','газированная','бутылка',3);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (22,'Швепс Тоник 0,5л','газированная','бутылка',1.3);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (23,'Швепс Клюква 1л','газированная','бутылка',1.81);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (24,'Швепс Клюква 0,5л','газированная','бутылка',1.3);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (25,'Фьюз Ти Черный чай-Лимон 0,5л','негазированная','бутылка',1.27);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (26,'Фьюз Ти Черный чай-Лимон 1л','негазированная','бутылка',2.04);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (27,'Фьюз Ти Зеленый чай-клубника 0,5л','негазированная','бутылка',1.27);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (28,'Фьюз Ти Зеленый чай-клубника 1л','негазированная','бутылка',2.04);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (29,'Фьюз Ти Зеленый чай-клубника 1,5л','негазированная','бутылка',2.5);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (30,'Рич Апельсин 1л','сок','бутылка',2.85);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (31,'Рич Апельсин 0,2л','сок','бутылка',1.15);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (32,'Рич Яблоко 1л','сок','бутылка',2.85);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (33,'Рич Яблоко 0,2л','сок','бутылка',1.15);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (34,'Рич Манго 1л','сок','бутылка',2.85);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (35,'Рич Манго 0,2л','сок','бутылка',1.15);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (36,'Рич Вишня 1л','сок','бутылка',2.85);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (37,'Рич Вишня 0,2л','сок','бутылка',1.19);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (38,'Рич Томат 1л','сок','бутылка',2.85);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (39,'Добрый Морс 1л','сок','бутылка',1.89);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (40,'Добрый Морс 2л','сок','бутылка',4.3);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (41,'Добрый Персик-Яблоко 1л','сок','бутылка',1.74);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (42,'Добрый Апельсин 0,33л','сок','бутылка',1.14);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (43,'Добрый Апельсин 2л','сок','бутылка',3.35);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (44,'БонАква 0,5л','негазированная','бутылка',0.86);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (45,'БонАква 1л','негазированная','бутылка',1.1);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (46,'БонАква 1,5л','негазированная','бутылка',1.35);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (47,'БонАква 2л','негазированная','бутылка',1.46);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (48,'БонАква Лимон 0,5л','негазированная','бутылка',1.35);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (49,'БонАква Лимон 1л','негазированная','бутылка',1.89);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (50,'Палпи 1л','негазированная','бутылка',2.64);
INSERT INTO `` (`idproduct`,`name`,`category`,`measurement`,`price`) VALUES (51,'Палпи Апельсин 0,5л','негазированная','бутылка',1.19);

INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (1,2,32,80,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (2,2,29,25,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (3,2,34,-90,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (4,2,28,96,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (5,2,1,40,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (6,2,3,34,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (7,2,27,12,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (8,2,34,-3,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (9,2,8,-23,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (10,2,2,100,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (11,2,38,13,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (12,2,8,80,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (13,2,47,77,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (14,2,36,80,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (15,2,4,90,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (16,2,5,37,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (17,2,6,12,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (18,2,10,78,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (19,2,36,120,'08/12/2019');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (20,1,32,-20,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (21,1,4,-12,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (22,1,36,-9,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (23,1,5,-5,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (24,1,37,-12,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (25,1,6,-20,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (26,1,7,-30,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (27,1,8,-8,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (28,1,12,-9,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (29,1,44,-30,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (30,1,45,-9,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (31,1,46,-12,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (32,1,47,-20,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (33,3,2,20,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (34,3,3,8,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (35,3,35,20,' 09/12/2019 ');
INSERT INTO `` (`id_sklad_product`,`sklad_idsklad`,`product_idproduct`,`quantity`,`date`) VALUES (36,2,4,-4,' 09/12/2019 ');

INSERT INTO `` (`idsklad`,`fax`,`address`) VALUES (1,'+375(222) 56-43-34','Беларусь, г.Могилев, ул.Колужская 33');
INSERT INTO `` (`idsklad`,`fax`,`address`) VALUES (2,'+375(152) 88-12-12','Беларусь, г.Гродно, ул. Герасимовича 1А');
INSERT INTO `` (`idsklad`,`fax`,`address`) VALUES (3,'+375(172) 90-15-66','Беларусь, г. Минск, ул. Скорины 50');

INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (17,'admin','admin','admin','active');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (18,'w12orker','w12Orker','worker','active');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (19,'customer49','customer','customer','active');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (20,'cust14omer','cust14omer','customer','reserved');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (21,'oleg3414','Ol234eg','customer','blocked');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (22,'logis11ik1-285897814','SK45lad1','worker','fired');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (23,'logis11ik1-637444167','SK45lad1','worker','fired');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (24,'logis11ik11700563413','SK45lad1','worker','fired');
INSERT INTO `` (`iduser`,`login`,`password`,`role`,`status`) VALUES (25,'logis11ik11812625245','SK45lad1','worker','active');

INSERT INTO `` (`idworker`,`user_iduser`,`surname`,`name`,`seniority`,`phone`,`address`) VALUES (10,18,'Петр','Алексей',2.3,'(29)-125-78-89','Беларусь, г.Минск, ул. Борисовская 1 кв.12');
INSERT INTO `` (`idworker`,`user_iduser`,`surname`,`name`,`seniority`,`phone`,`address`) VALUES (11,22,'Морвыв','Марина',1.5,'(33)900-23-23','Беларусь,   г.Могилев,   ул. Молчанова 2 кв.1');
INSERT INTO `` (`idworker`,`user_iduser`,`surname`,`name`,`seniority`,`phone`,`address`) VALUES (12,23,'Шаповал','Надежд',0.5,'(29)-323-23-23','Беларусь,  г.Гродно,  ул. Шишкова 12 кв.8');
INSERT INTO `` (`idworker`,`user_iduser`,`surname`,`name`,`seniority`,`phone`,`address`) VALUES (13,24,'Тутор','Кирилл',0.5,'(29)-992-01-01','Белурась,г.Гродно,ул.Л.Беды 4');
INSERT INTO `` (`idworker`,`user_iduser`,`surname`,`name`,`seniority`,`phone`,`address`) VALUES (14,25,'Медведева','Алина',1.5,'(29)-333-23-88','Беларусь, Брест, ул Гаврилова 14');
