-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 22:58:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema logist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logist` DEFAULT CHARACTER SET utf8 ;
USE `logist` ;

-- -----------------------------------------------------
-- Table `logist`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`customer` (
  `idcustomer` INT(11) NOT NULL AUTO_INCREMENT,
  `user_iduser` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `representative` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcustomer`),
  UNIQUE INDEX `idcustomer_UNIQUE` (`idcustomer` ASC) VISIBLE,
  INDEX `fk_customer_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `logist`.`user` (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`sklad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`sklad` (
  `idsklad` INT(11) NOT NULL AUTO_INCREMENT,
  `fax` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsklad`),
  UNIQUE INDEX `fax_UNIQUE` (`fax` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`order` (
  `idorder` INT(11) NOT NULL AUTO_INCREMENT,
  `sklad_idsklad` INT(11) NOT NULL,
  `customer_idcustomer` INT(11) NOT NULL,
  `orderdate` VARCHAR(45) NOT NULL,
  `deliverydate` VARCHAR(45) NOT NULL,
  `processing` VARCHAR(45) NOT NULL,
  `cost` DOUBLE NOT NULL,
  PRIMARY KEY (`idorder`, `sklad_idsklad`, `customer_idcustomer`),
  INDEX `fk_order_sklad1_idx` (`sklad_idsklad` ASC) VISIBLE,
  INDEX `fk_order_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `logist`.`customer` (`idcustomer`),
  CONSTRAINT `fk_order_sklad1`
    FOREIGN KEY (`sklad_idsklad`)
    REFERENCES `logist`.`sklad` (`idsklad`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`product` (
  `idproduct` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `measurement` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`order_product` (
  `id_order_product` INT(11) NOT NULL AUTO_INCREMENT,
  `order_idorder` INT(11) NOT NULL,
  `product_idproduct` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  PRIMARY KEY (`id_order_product`, `order_idorder`, `product_idproduct`),
  INDEX `fk_order_product_order1_idx` (`order_idorder` ASC) VISIBLE,
  INDEX `fk_order_product_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `logist`.`order` (`idorder`),
  CONSTRAINT `fk_order_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `logist`.`product` (`idproduct`))
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`sklad_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`sklad_product` (
  `id_sklad_product` INT(11) NOT NULL AUTO_INCREMENT,
  `sklad_idsklad` INT(11) NOT NULL,
  `product_idproduct` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sklad_product`, `sklad_idsklad`, `product_idproduct`),
  INDEX `fk_skladproduct_sklad1_idx` (`sklad_idsklad` ASC) VISIBLE,
  INDEX `fk_skladproduct_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_skladproduct_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `logist`.`product` (`idproduct`),
  CONSTRAINT `fk_skladproduct_sklad1`
    FOREIGN KEY (`sklad_idsklad`)
    REFERENCES `logist`.`sklad` (`idsklad`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `logist`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logist`.`worker` (
  `idworker` INT(11) NOT NULL AUTO_INCREMENT,
  `user_iduser` INT(11) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `seniority` DOUBLE NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idworker`),
  INDEX `fk_worker_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_worker_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `logist`.`user` (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
